### ISSUE TITLE
Problem with NodeMCU upload

### ISSUE THREAD

**Issue by pvtoari** [spacehuhn/esp8266_deauther#1668]
> Have you searched for existing (open and closed) issues describing the same problem?

Yes

**Describe the error**
Whenever I try to upload the deauther code to my nodemcu board it just throws the same error that I show on the image

```
Traceback (most recent call last):
  File "C:\Users\ariel\AppData\Local\Arduino15\packages\deauther\hardware\esp8266\2.7.5/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/ariel/AppData/Local/Arduino15/packages/deauther/hardware/esp8266/2.7.5/tools/esptool\esptool.py", line 2890, in main
    esp.connect(args.before)
  File "C:/Users/ariel/AppData/Local/Arduino15/packages/deauther/hardware/esp8266/2.7.5/tools/esptool\esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
Failed uploading: uploading error: exit status 1
```

**Expected behavior**
Expected to flash correctly the board :(

**Screenshots**
![imagen](https://github.com/SpacehuhnTech/esp8266_deauther/assets/43178469/e1d906ab-3b1b-43a1-ad07-8415bd0f3e80)

**Environment (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Firefox
 - Version idk (latest?)
 - Hardware DIY

**Attempts**
I tried to update every neccesary driver from NodeMCU or ArduinoIDE and nothing seems to work.

**Additional context**
I read in a forum that it might be an hardware error and my board might be defective. Help guys :[

**Comment by ktauchathuranga** [comment]
did you installed the correct board manger and select the board from that board manger?
`https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json`

and do you have anything connected to nodemcu? i mean in any of the GPIO's?

**Comment by MOUSEHACKER1** [comment]
Mi hermano la verdad parece ser un problema con windows 11 en mi equipo me toco instalar en una particion aparte w10 para que me dejara, si alguien sabe como solucionarlo en w11 lo agradecemos.  <3
