### ISSUE TITLE
flakey utils/web_converter_python/webConverter.py

### ISSUE THREAD

**Issue by tobozo** [spacehuhn/esp8266_deauther#787]
Been trying for a couple of hours to make this script run on four different environments (including Travis CI) with just total failure.

I know it's working because I have it working at home. 
Maybe it just needs to be standardized so it works in a VM (e.g. travis ci) and everywhere else without totally messing the existing environment ?

I wish I could help on those points but have no idea if they're originating in my own clumsiness.

- incomplete readme: should specify the required major/minor version of python, currently we can only assume the major version
- confusing installation instructions: uses "python3" and "pip" in the same command line, but this is only available on x64 architectures! 
- missing requirements.txt: only one package is listed, and it's optional, but there are more dependencies

Suggestion: since python versions 2.xx and 3.xx are already spreading fuckery on every system they invade (especially tensorflow:), it would be much better to use the older 2.7x version and stick with it.

Travis CI seems to hate it:

```
Traceback (most recent call last):
  File "webConverter.py", line 11, in <module>
    from css_html_js_minify.minify import process_single_html_file, process_single_js_file, process_single_css_file
  File "/home/travis/build/tobozo/esp8266_deauther/utils/web_converter_python/css_html_js_minify/__init__.py", line 13, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "/home/travis/build/tobozo/esp8266_deauther/utils/web_converter_python/css_html_js_minify/minify.py", line 30, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
  File "/usr/local/lib/python3.4/dist-packages/anglerfish/__init__.py", line 33, in <module>
    from anglerfish.make_beep import beep  # noqa
  File "/usr/local/lib/python3.4/dist-packages/anglerfish/make_beep.py", line 13, in <module>
    from subprocess import run
ImportError: cannot import name 'run'
```

and the most hilarious:

```
Traceback (most recent call last):
  File "webConverter.py", line 12, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```

I'm not good enough to rewrite this in python, but I could easily make a PHP script out of it, and make it work on PHP4, PHP5, and PHP7, without forcing the user to create conflicts on an existing system.

**Comment by tobozo** [comment]
ping @xdavidhu 

`    except ModuleNotFoundError:`

solved by applying [this patch](https://github.com/tobozo/esp8266_deauther/commit/eca5e0c90dfa96431a1cf51313a7ed9c105e7fe6) (will submit a PR soon if it's a valid fix)

Previous compilation/version mismatch errors were solved by using python 3.6 and pip 9.0.1, and installing anglerfish without `sudo python3 -m`.
